server:
  port: 0

spring:
  application:
    name: order-service

  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test;
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true   //운영할 때는 system.out로 sql를 보여주기때문에 쓰지 말아야한다
        format_sql: true  //sql 이쁘게 보이게
        default_batch_fetch_size: 100
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.msa.orderservice: DEBUG
